attr_map = {
    "Alcohol": {
        "'beer_and_wine'": 0,
        "'full_bar'": 1,
        "'none'": None,
        None: None,
        'None': None,
        "u'beer_and_wine'": 0,
        "u'full_bar'": 1,
        "u'none'": None,
    },
    "BikeParking": {
        "False": 0,
        None: None,
        "True": 1,
    },
    "BusinessAcceptsCreditCards": {
        "False": 0,
        None: None,
        "None": None,
        "True": 1,
    },
    "DriveThru": {
        "False": 0,
        None: None,
        "None": None,
        "True": 1,
    },
    "NoiseLevel": {
        "'average'": 1,
        "'loud'": 2,
        "'quiet'": 0,
        "'very_loud'": 3,
        None: None,
        'None': None,
        "u'average'": 1,
        "u'loud'": 2,
        "u'quiet'": 0,
        "u'very_loud'": 3,
    },
    "OutdoorSeating": {
        "False": 0,
        None: None,
        "None": None,
        "True": 1,
    },
    "RestaurantsDelivery": {
        "False": 0,
        None: None,
        "None": None,
        "True": 1,
    },
    "RestaurantsTakeOut": {
        "False": 0,
        None: None,
        "None": None,
        "True": 1,
    },
    "WiFi": {
        "'free'": 0,
        "'no'": 1,
        "'paid'": 2,
        None: None,
        'None': None,
        "u'free'": 0,
        "u'no'": 1,
        "u'paid'": 2,
    }
}